sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tJ7PyTwUyubkVn52xei
    accessKeySecret: 5TsjIvUsXtvhmIaZ7w7Fbx7t7yjvP0
    bucketName: web-tlias-cgr
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10